#!/usr/bin/env ruby

require_relative 'lib/services/s3_service'
require_relative 'lib/services/aws_provisioner'
require_relative 'config/services'

puts "🪣 S3 Service & AWS Infrastructure Test"
puts "======================================"

begin
  # Initialize services
  puts "\n🔧 Initializing services..."
  
  s3_service = S3Service.new
  aws_provisioner = AWSProvisioner.new
  
  puts "✅ Services initialized successfully!"
  
  # Check infrastructure status
  puts "\n🔍 Checking infrastructure status..."
  status_result = aws_provisioner.check_infrastructure_status
  
  if status_result[:success]
    puts "✅ All infrastructure components are ready!"
  else
    puts "⚠️  Some infrastructure components are missing."
    puts "Would you like to provision the infrastructure? (y/n)"
    response = gets.chomp.downcase
    
    if response == 'y'
      puts "\n🚀 Provisioning infrastructure..."
      provision_result = aws_provisioner.provision_infrastructure
      
      if provision_result[:success]
        puts "✅ Infrastructure provisioning completed!"
      else
        puts "❌ Infrastructure provisioning failed: #{provision_result[:error]}"
        exit 1
      end
    else
      puts "❌ Infrastructure required. Please run provisioning first."
      exit 1
    end
  end
  
  # Test infrastructure connectivity
  puts "\n🧪 Testing infrastructure connectivity..."
  test_result = aws_provisioner.test_infrastructure
  
  unless test_result[:success]
    puts "❌ Infrastructure tests failed. Please check your AWS configuration."
    exit 1
  end
  
  puts "✅ Infrastructure connectivity verified!"
  
  # Get infrastructure details
  puts "\n📋 Infrastructure Details:"
  details = aws_provisioner.get_infrastructure_details
  
  details.each do |component, info|
    if info.is_a?(Hash) && info[:error]
      puts "  ❌ #{component}: #{info[:error]}"
    elsif info.is_a?(Hash)
      puts "  ✅ #{component}:"
      info.each do |key, value|
        puts "    #{key}: #{value}"
      end
    end
  end
  
  # Example S3 operations (commented out since we don't have actual images)
  puts "\n📝 Example S3 Operations:"
  puts "```ruby"
  puts "# Create bucket (if needed)"
  puts "result = s3_service.create_bucket('my-burns-videos', {"
  puts "  lifecycle_days: 14,"
  puts "  versioning: true,"
  puts "  cors: true"
  puts "})"
  puts ""
  puts "# Upload project images"
  puts "upload_result = s3_service.upload_project_images("
  puts "  'project-123',"
  puts "  generated_images,"
  puts "  'burns-videos'"
  puts ")"
  puts ""
  puts "# Create project manifest"
  puts "manifest_result = s3_service.create_project_manifest("
  puts "  'project-123',"
  puts "  project_data,"
  puts "  'burns-videos'"
  puts ")"
  puts ""
  puts "# List project files"
  puts "files = s3_service.list_project_files('project-123', 'burns-videos')"
  puts ""
  puts "# Clean up old projects"
  puts "cleanup_result = s3_service.cleanup_old_projects('burns-videos', 14)"
  puts "```"
  
  # Show S3 bucket structure
  puts "\n📁 S3 Bucket Structure:"
  puts "```"
  puts "burns-videos/"
  puts "├── projects/"
  puts "│   ├── project-123/"
  puts "│   │   ├── images/"
  puts "│   │   │   ├── modern_smartphone_20241201_143022.jpg"
  puts "│   │   │   ├── tech_workspace_20241201_143023.jpg"
  puts "│   │   │   └── ..."
  puts "│   │   └── manifest.json"
  puts "│   ├── project-456/"
  puts "│   │   ├── images/"
  puts "│   │   └── manifest.json"
  puts "│   └── ..."
  puts "└── videos/"
  puts "    ├── project-123_final_video.mp4"
  puts "    └── ..."
  puts "```"
  
  # Show lifecycle policy
  puts "\n⏰ Lifecycle Policy:"
  puts "  • Projects older than 14 days are automatically deleted"
  puts "  • Helps manage storage costs"
  puts "  • Configurable via bucket settings"
  
  # Show security features
  puts "\n🔒 Security Features:"
  puts "  • IAM roles and policies for secure access"
  puts "  • Presigned URLs for temporary access"
  puts "  • Metadata tracking for all uploads"
  puts "  • Versioning support (optional)"
  
  # Show integration with pipeline
  puts "\n🔄 Pipeline Integration:"
  puts "  1. Images generated by ImageGenerator"
  puts "  2. Uploaded to S3 via S3Service"
  puts "  3. Manifest created with project metadata"
  puts "  4. Lambda function processes images from S3"
  puts "  5. Final video uploaded back to S3"
  
rescue => e
  puts "\n❌ Error: #{e.message}"
  puts "\nTo fix this:"
  puts "1. Install AWS SDK: gem install aws-sdk-s3"
  puts "2. Configure AWS credentials: aws configure"
  puts "3. Set environment variables:"
  puts "   export AWS_ACCESS_KEY_ID='your_key'"
  puts "   export AWS_SECRET_ACCESS_KEY='your_secret'"
  puts "   export AWS_REGION='us-east-1'"
end

puts "\n🚀 Next Steps:"
puts "1. Install AWS SDK: gem install aws-sdk-s3"
puts "2. Configure AWS credentials: aws configure"
puts "3. Provision infrastructure: ruby provision_aws.rb"
puts "4. Test S3 operations with real images"
puts "5. Build Lambda video generation function"

puts "\n📚 Documentation:"
puts "  • AWS SDK for Ruby: https://docs.aws.amazon.com/sdk-for-ruby/"
puts "  • S3 API Reference: https://docs.aws.amazon.com/s3/"
puts "  • Lambda API Reference: https://docs.aws.amazon.com/lambda/" 